version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple_investment_platform:latest
    container_name: rails_app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/app_production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "80:80"
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_production
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data:
