default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432


development:
  <<: *default
  database: sip_development
  host: <%= ENV.fetch('DATABASE_HOST', '') %>
  username: <%= ENV.fetch('DATABASE_USER', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>


test:
  <<: *default
  database: simple_investment_platform_test

production:
  primary: &primary_production
    <<: *default
    database: simple_investment_platform_production
    username: ENV["SIMPLE_INVESTMENT_PLATFORM_DATABASE_USER"]
    password: <%= ENV["SIMPLE_INVESTMENT_PLATFORM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: simple_investment_platform_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: simple_investment_platform_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: simple_investment_platform_production_cable
    migrations_paths: db/cable_migrate
